name: Code Quality and Documentation

on: 
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint-and-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff sphinx sphinx-rtd-theme sphinx-autoapi

    - name: Get changed files
      id: changed-files
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr diff --name-only | grep ".py$" > modFiles.txt
        echo "files=$(cat modFiles.txt | tr '\n' ' ')" >> $GITHUB_OUTPUT
      
    - name: Run Ruff linting
      if: steps.changed-files.outputs.files != ''
      run: |
        for file in $(cat modFiles.txt); do
          ruff check $file --config ./pyproject.toml || exit 1
        done

    - name: Build documentation
      if: steps.changed-files.outputs.files != ''
      run: |
        make -C docs clean
        make -C docs html

    - name: Deploy documentation
      env:
        DOCS_REPO: "AaravAgarwal/doc_test_3"
        DOCS_TOKEN: ${{ secrets.DOCPUSHING }}
      run: |
        # Configure git
        git config --global user.email "aarav3@illinois.edu"
        git config --global user.name "GitHub Actions"

        # Clone docs repository
        git clone "https://x-access-token:${DOCS_TOKEN}@github.com/${DOCS_REPO}.git" external-docs

        # Create repo-specific directory
        REPO_NAME=$(basename "$GITHUB_REPOSITORY")
        TARGET_DIR="external-docs/${REPO_NAME}-docs"
        mkdir -p "$TARGET_DIR"

        # Copy generated docs
        cp -R docs/build/html/* "$TARGET_DIR/"

        # Commit and push
        cd external-docs
        git add .
        git commit -m "Docs update: ${GITHUB_SHA}"
        git push origin main
