name: Ruff Linter and Sphinx Documentation Generation

on: 
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  initDependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
        shell: bash

  FindChangedFiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Find Changed files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{github.event.pull_request._links.html.href }}
        run: |
          touch modFiles.txt
          cat <<EOF | grep ".py$" | tee modFiles.txt
          $(gh pr diff  "$URL" --name-only)
          EOF
          echo "filePath=modFiles.txt" >> $GITHUB_ENV
        shell: bash
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: changedFiles
          path: ${{ env.filePath }}
          retention-days: 1

  RunRuff:
    runs-on: ubuntu-latest
    needs: [FindChangedFiles, initDependencies]
    steps:
      - uses: actions/checkout@v3
      - name: Install Ruff
        run: |
          pip install ruff
        shell: bash
      - name: Download changedFiles
        uses: actions/download-artifact@v3
        with:
          name: changedFiles
      - name: Run linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in $(cat modFiles.txt); 
          do 
          ruff check ${file} --config ./pyproject.toml
          done;
        shell: bash

  BuildDocs:
    runs-on: ubuntu-latest
    needs: initDependencies
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
 
      - name: Install Sphinx and Dependencies
        run: |
          pip install sphinx sphinx-rtd-theme sphinx-autoapi
          pip install sphinx-autoapi
      
      - name: Build Sphinx documentation
        run: |
          sphinx-build -M html ./ ./docs

      - name: List generated files
        run: |
          ls -R docs/html

      - name: Push HTML files to docs repo
        env:
          GITHUB_TOKEN: ${{ secrets.DOCPUSHING }}  # Ensure this token has access to doc_test_2
        run: |
          git config --global user.email "aarav3@illinois.edu"
          git config --global user.name "AaravAgarwal"
          
          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/AaravAgarwal/doc_test_2.git
          cp -R docs/html/* strat-telem-documentation/
          cd strat-telem-documentation
          git add .
          git commit -m "Update Apollo Sphinx documentation HTML"
          git push origin main

          # sphinx.ext.intersphinx
